/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Equipamento;

import dao.ClienteDAO;
import dao.EquipamentoDAO;
import elitetesystem.frmCliente;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Equipamento;

/**
 *
 * @author DC CENTER PAES
 */
public class InserirEquipamento extends javax.swing.JDialog {

    /**
     * Creates new form InserirEquipamento
     */
    private Long CodCliente;
    private Equipamento equipamento;
    EquipamentoDAO equipamentoDAO = new EquipamentoDAO();
    private boolean alterar;
    private Long codigoRetorno;

    public InserirEquipamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        URL url = this.getClass().getResource("/imagens/ELITETECLOGO.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        txtCliente.setEditable(false);
        txtCliente.setEnabled(false);
        txtDescricao.setEnabled(false);
        cmbTipoEquipamento.setEnabled(false);
        cmbStatus.setEnabled(false);
        cmbStatusEquipamento.setEnabled(false);
        txtNSerie.setEnabled(false);
        txtCliente.setFocusable(false);

    }

    public InserirEquipamento(java.awt.Frame parent, boolean modal, boolean alterar, final Equipamento equipamento) {
        super(parent, modal);
        initComponents();

        this.alterar = alterar;
        if (alterar) {
            this.equipamento = equipamento;
            txtCliente.setText(equipamento.getCliente());
            txtDescricao.setText(equipamento.getDescricao());
            txtNSerie.setText(equipamento.getNserie());
            try {
                String GetStatus;
                GetStatus = equipamento.getStatus();
                if (GetStatus.equals("Aguardando")) {
                    cmbStatus.setSelectedIndex(1);
                }
                if (GetStatus.equals("Em execução")) {
                    cmbStatus.setSelectedIndex(2);
                }
                if (GetStatus.equals("Concluído")) {
                    cmbStatus.setSelectedIndex(3);
                }
                if (GetStatus.equals("Condenado")) {
                    cmbStatus.setSelectedIndex(4);
                }
                if (GetStatus.equals("Com Defeito")) {
                    cmbStatus.setSelectedIndex(5);
                }
            } catch (Exception e) {
            }
            try {
                String GetStatusEquipamento;
                GetStatusEquipamento = equipamento.getStatusEquipamento();
                if (GetStatusEquipamento.equals("Contrato")) {
                    cmbStatusEquipamento.setSelectedIndex(2);
                }
                if (GetStatusEquipamento.equals("Avulso")) {
                    cmbStatusEquipamento.setSelectedIndex(1);
                }
            } catch (Exception e) {
            }
            try {
                String GetTipo;
                GetTipo = equipamento.getTipo();
                if (GetTipo.equals("Computador")) {
                    cmbTipoEquipamento.setSelectedIndex(1);
                }
                if (GetTipo.equals("Notebook")) {
                    cmbTipoEquipamento.setSelectedIndex(2);
                }
                if (GetTipo.equals("Impressora")) {
                    cmbTipoEquipamento.setSelectedIndex(3);
                }
                if (GetTipo.equals("Tablet")) {
                    cmbTipoEquipamento.setSelectedIndex(4);
                }
                if (GetTipo.equals("NetBook")) {
                    cmbTipoEquipamento.setSelectedIndex(5);
                }
                if (GetTipo.equals("Celular")) {
                    cmbTipoEquipamento.setSelectedIndex(6);
                }
                if (GetTipo.equals("Nobreak")) {
                    cmbTipoEquipamento.setSelectedIndex(7);
                }
                if (GetTipo.equals("Ultrabook")) {
                    cmbTipoEquipamento.setSelectedIndex(8);
                }
                if (GetTipo.equals("AIO")) {
                    cmbTipoEquipamento.setSelectedIndex(9);
                }
            } catch (Exception e) {
            }


        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnBuscaCliente = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        cmbTipoEquipamento = new javax.swing.JComboBox();
        cmbStatusEquipamento = new javax.swing.JComboBox();
        cmbStatus = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtNSerie = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Novo Equipamento");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Adicionar novo Equipamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setText("Cliente:");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Tipo:");

        jLabel4.setText("Status Equipamento:");

        jLabel5.setText("Status Serviço:");

        btnBuscaCliente.setText("...");
        btnBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaClienteActionPerformed(evt);
            }
        });

        cmbTipoEquipamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbTipoEquipamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Selecione", "Computador", "Notebook", "Impressora", "Tablet", "NetBook", "Celular", "Nobreak", "UltraBook", "AIO" }));
        cmbTipoEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoEquipamentoActionPerformed(evt);
            }
        });

        cmbStatusEquipamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbStatusEquipamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Avulso", "Contrato" }));
        cmbStatusEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusEquipamentoActionPerformed(evt);
            }
        });

        cmbStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Aguardando", "Em execução", "Concluído", "Condenado", "Com Defeito" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });

        jLabel6.setText("Nº Série interno:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricao)
                            .addComponent(cmbTipoEquipamento, 0, 705, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbStatus, 0, 705, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscaCliente))
                                    .addComponent(cmbStatusEquipamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNSerie)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTipoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbStatusEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1323972017_fechar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1324324710_registro.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 639, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!alterar) {
            equipamento = new Equipamento();
        }
        equipamento.setDescricao(txtDescricao.getText());
        equipamento.setCliente(txtCliente.getText());
        equipamento.setNserie(txtNSerie.getText());
        equipamento.setStatus(cmbStatus.getSelectedItem().toString());
        equipamento.setStatusEquipamento(cmbStatusEquipamento.getSelectedItem().toString());
        equipamento.setTipo(cmbTipoEquipamento.getSelectedItem().toString());
        equipamento.setStatusControle("ATIVO");

        boolean retorno = false;
        if (!alterar) {
            retorno = equipamentoDAO.gravar(equipamento);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Equipamento Salvo com Sucesso!!");
                this.dispose();
            }
        } else {
            retorno = equipamentoDAO.gravar(equipamento);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Equipamento alterado com sucesso!!");
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cmbTipoEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoEquipamentoActionPerformed

    private void btnBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaClienteActionPerformed
        frmCliente j = new frmCliente(null, true);
        j.setLocationRelativeTo(null);
        j.setVisible(true);
        CodCliente = j.getCodigoRetorno();

        ClienteDAO clienteDAO = new ClienteDAO();

        txtCliente.setText(clienteDAO.getClienteByCodigo(CodCliente).getNome());


        txtCliente.setEnabled(true);
        txtDescricao.setEnabled(true);
        cmbTipoEquipamento.setEnabled(true);
        cmbStatus.setEnabled(true);
        cmbStatusEquipamento.setEnabled(true);
        txtNSerie.setEnabled(true);
        txtDescricao.grabFocus();


    }//GEN-LAST:event_btnBuscaClienteActionPerformed

    private void cmbStatusEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusEquipamentoActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                InserirEquipamento dialog = new InserirEquipamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbStatus;
    private javax.swing.JComboBox cmbStatusEquipamento;
    private javax.swing.JComboBox cmbTipoEquipamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNSerie;
    // End of variables declaration//GEN-END:variables
}
